### PR TITLE
cross-build to 2.11, 2.12 & 2.13

### LINKED ISSUE #18: cross publish for 2.13
Is that possible to cross publish this awesome rule for Scala 2.13?

### PR DESCRIPTION
**Pull request by bjaglin**
See https://github.com/scalacenter/scalafix/issues/1108

Leverages https://github.com/scalacenter/scalafix/pull/1118

Closes https://github.com/NeQuissimus/sort-imports/issues/18

### CODE REVIEW

**Comment by NeQuissimus** [comment]
I guess we're going to find out if the GitHub workflows need adjustments :)

**Comment by NeQuissimus** [comment]
Thank you!

**Comment by NeQuissimus** [comment]
https://github.com/NeQuissimus/sort-imports/runs/731629700?check_suite_focus=true
I think the release job will need to explicitly release 2.11 and 2.13

**Comment by bjaglin** [comment]
Indeed, I somehow assumed `sbt-release-early` would do it automatically. I just sent-in https://github.com/NeQuissimus/sort-imports/pull/67 :crossed_fingers:

**Pull request merged**
